
apiVersion: v1

kind: Service

metadata:

  name: chatbot-api-svc

spec:

  selector:

    app: chatbot-api

  ports:

    - port: 80

      protocol: TCP

      targetPort: 3000

  type: LoadBalancer
